### ISSUE TITLE
Getting "Import Error: No module named Foundation"

### ISSUE THREAD

**Issue by EvanLovely** [rjames86/download_pinboard#5]
It may be due to the fact that I installed my `python` using Homebrew. See the commands entered in the screenshot below and let me know what I'm missing; thanks!!

![evan_ebook-2____dropbox_scripts_download_pinboard__zsh_](https://cloud.githubusercontent.com/assets/569699/8269783/fac60e32-176e-11e5-926e-8b7c07b6400c.png)

**Comment by rjames86** [comment]
Looks like this may solve your problem

https://github.com/Homebrew/homebrew/issues/19043#issuecomment-18297773

>The CoreFoundation module comes from PyObjC which Apple pre-installs on OS X. It has to be installed separately through easy_install/pip if you want to use it with homebrew's Python: http://pythonhosted.org/pyobjc/install.html

**Comment by EvanLovely** [comment]
Thanks! That got me past those errors, now I'm getting this:

    ImportError: No module named dateutil.tz

**Comment by rjames86** [comment]
Thanks! Looks like I might need to do a requirements file for this :(

    sudo pip install python-dateutil

I may also need to rework some things to make it not have any dependencies, but the PyObj stuff makes it a lot easier to read/write to defaults

**Comment by EvanLovely** [comment]
Sweet; that did it!

**Comment by EvanLovely** [comment]
Also, since you asked about performance feedback; your slick script imported my 1,464 bookmarks just fine on the first run :) Thanks! :beers:
