### ISSUE TITLE
Feature Request: Pinboard Description field saved into Spotlight Comments

### ISSUE THREAD

**Issue by EvanLovely** [rjames86/download_pinboard#6]
Would help with search results! :)

**Comment by rjames86** [comment]
Are you sure it's not already?

https://github.com/rjames86/download_pinboard/blob/master/lib/download_pinboard.py#L90

**Comment by EvanLovely** [comment]
Yep, check out this screenshot:

![default_sorter_and_what_the_heck_is_the_event_loop_anyway__ _philip_roberts_webloc_info_and_pinboard__bookmarks_for_evanlovely_and_evan_ebook-2____dropbox_library_bookmarks__zsh_](https://cloud.githubusercontent.com/assets/569699/8269974/b0485838-1778-11e5-8eae-cb1f29c76280.png)

**Comment by rjames86** [comment]
I thought the `'description'` key would have done that from Pinnboard. Turns out there's an `'extended'` key that does it. Give this branch a try

https://github.com/rjames86/download_pinboard/tree/extended_description
